---

driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_ruby_for_busser: true
  group_vars_path: local
  require_chef_for_busser: false
  extra_vars:
    env: local

transport:
  max_ssh_sessions: 6
  connection_retries: 5

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: trusty
    driver_config:
      box: ubuntu/trusty64

  - name: xenial
    driver_config:
      box: ubuntu/xenial64

  - name: centos7
    driver_config:
      box: puppetlabs/centos-7.0-64-nocm

suites:
  - name: pip
    provisioner:
      hosts: pip
