---

driver:
  name: docker
  # Workaround for test-kitchen/kitchen-docker Issue #207
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_ruby_for_busser: true
  require_chef_for_busser: false

transport:
  max_ssh_sessions: 6
  connection_retries: 5

busser:
  ruby_bindir: /usr/bin

verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
  - name: fedora-26
  - name: fedora-25
  - name: fedora-24
  - name: debian-8

suites:
  - name: pip
    run_list:
    attributes:
