FROM centos/ruby-22-centos7

USER root

# Install Ansible
RUN yum install -y git epel-release
RUN yum install -y ansible

# Install Ansible inventory file
RUN printf "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

USER default

RUN /bin/bash -c "gem install serverspec"
