FROM centos/ruby-22-centos7

# Install Ansible
RUN yum install -y git epel-release
RUN yum install -y ansible
RUN gem install serverspec

# Install Ansible inventory file
RUN printf "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
