FROM centos:7
RUN yum update

# Install Ansible
RUN yum install -y git epel-release
RUN yum install -y ansible

# Install Ansible inventory file
RUN echo -e "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
